server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/game_sync
      auto-index-creation: true

  redis:
    host: localhost
    port: 6379
    timeout: 60000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: game-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
cache:
  ttl: 600

